### ISSUE TITLE
Import on Windows fails

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal_DatasEt_compaRator#3]
I have set up the conda environment as it is described in the readme (but using the full conda, not mini conda) on my Windows system:

$ conda create --name ChemIcal_DatasEt_compaRator python=3.8
$ conda activate ChemIcal_DatasEt_compaRator
$ conda install pip
$ python -m pip install -U pip #Upgrade pip
$ pip install notebook rdkit-pypi matplotlib==3.5.1 seaborn==0.11.2 chemplot==1.2.0 matplotlib_venn==0.11.6 FPDF==1.7.2

When I execute the import cell in the tutorial notebook, I get an import error saying that the rdBase dll has not been found:
![image](https://user-images.githubusercontent.com/44881147/175056958-746fac13-89fb-450f-b077-950fee89116f.png)

Any ideas or suggestions?

**Comment by Kohulan** [comment]
@JonasSchaub Could you check with python 3.7.9 ?

**Comment by OBrink** [comment]
I cannot reproduce the problem on Windows 11. When I execute the installation code above, and run "from rdkit import Chem" in my Python shell, it works without problems

**Comment by JonasSchaub** [comment]
@Kohulan downgrading to python 3.7.9 seems to work, even though the import (from rdkit import Chem) took a looong time. But of course, it is not an ideal solution. I will have a look at the stackoverflow thread you sent me tomorrow (https://stackoverflow.com/questions/41365446/how-to-resolve-importerror-dll-load-failed-on-python). 
And I'm also on Windows 11.

**Comment by Kohulan** [comment]
Probably having multiple python versions installed also could be a problem.

**Comment by JonasSchaub** [comment]
Dear all,
I now got it working with Python 3.8. But I fetched RDKit from conda-forge instead of pypi. This is the recommended way for Windows, according to the RDKit documentation (https://www.rdkit.org/docs/Install.html).
Here is what I did:

conda create -c conda-forge -n ChemIcal_DatasEt_compaRator rdkit python=3.8
conda activate ChemIcal_DatasEt_compaRator
conda install pip
python -m pip install -U pip
pip install .

The problem is, CIDER installed RDKit from pypi as well when it was installed in the last line. So I now have rdkit and rdkit-pypi in my environment (both version 2022.03.3). 
What do you think of this? Is it a problem at all? Should we take rdkit-pypi out of the cider installation file and tell people to install it the way I did? Or do you know a better way to get it working on Windows (i.e. getting the rdBase.dll from somewhere)?

**Comment by OBrink** [comment]
If the conda installation works and is up-to-date, then I would say that nothing speaks against using it. In order to avoid installing it twice, we just need to remove the dependency from setup.py

**Comment by JonasSchaub** [comment]
Thanks, Otto, I agree. Let's wait for what @Kohulan thinks when he is back.

**Comment by Kohulan** [comment]
@OBrink @JonasSchaub ,

I think removing rdkit from setup.py is not a good idea. The ultimate goal is to easy pip install from PyPI directly. I could see the problem with the windows users but removing the rdkit from setup is an extra step for Mac and Linux users. Maybe we could mention in readme for windows users to setup an environment with rdkit preinstalled.

**Comment by OBrink** [comment]
That's also fine by me.

**Comment by Kohulan** [comment]
Readme updated [here](https://github.com/hannbus/ChemIcal_DatasEt_compaRator/commit/9b7046e42bd15017e11a00f1717430f905f53814)
Maybe we have to check on different windows laptops and see what exactly causing the issue because I could see it works for @OBrink not for @JonasSchaub when installed via PyPI directly. I also think having two RDKit versions installed is not a good idea.

**Comment by OBrink** [comment]
Mhm, how about we get rid of RDKit and generate the descriptors using the CDK via JPype? <3

**Comment by JonasSchaub** [comment]
Hannah and I had the same problem that rdBase.dll was not part of the RDKit installation from pypi. From conda-forge, it seems to be included. Yes, Otto did not have the problem.

**Comment by OBrink** [comment]
But did specifying the Python version (3.7.9) not solve the issue? Could we not do that, throw out the conda installation and everyone is happy?

**Comment by Kohulan** [comment]
@OBrink I don't think that is a nice option for us but can consider it.
@JonasSchaub could you check how many RDKit versions are installed on your laptop, maybe multiple versions in multiple environments. Maybe a few of the versions could fetch the rdBase correctly.

**Comment by Kohulan** [comment]
> But did specifying the Python version (3.7.9) not solve the issue? Could we not do that, throw out the conda installation and everyone is happy?

Yes, I agree but I want to know what causes the issue only for @JonasSchaub, not you.

**Comment by JonasSchaub** [comment]
> @JonasSchaub could you check how many RDKit versions are installed on your laptop, maybe multiple versions in multiple environments. Maybe a few of the versions could fetch the rdBase correctly.

Well, the 2020.09.1.0 version of rdkit worked but that does not get us very far, I think. And I don't think the other rdkit versions on my machine are causing the problem because they are all installed in separate conda environments.

**Comment by Kohulan** [comment]
Yes, The separate RDKit versions should be on separate conda environments. But can you also check how many rdBase.dll is found on your PC?

**Comment by JonasSchaub** [comment]
Apparently, there is no rdBase DLL anywhere but an rdBase.pyd file instead. And importing this in __init__.py fails with the pypi version but works with the conda-forge version for some non-apparent reason. 

What does not work:
python 3.8.13
rdkit-pypi 2022.3.3

What does work:
python 3.8.13
rdkit 2022.03.3 (from conda-forge)

@OBrink , what are your versions?
