### ISSUE TITLE
Write unit tests and use pytest to automatically run all of them

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal_DatasEt_compaRator#5]

**Comment by JonasSchaub** [comment]
How you did it so far is correct, the used data set should be hard-wired in unit tests. It would even be wise to create a separate "test data" folder for this, to be able to change and adjust the tutorial and testing data Independently. 

Testing functions that use and return a lot of data as is the case here (whole molecule set as input, e.g. descriptor values for all of them as output) is a bit tricky indeed. 
You can start testing the "simple" things, like the number of duplicates in your data sets or the size of the overlaps between them (if you have not already done these things). 
For things like descriptor value calculation, you could maybe use a dummy data set consisting of 1-3 molecules and specifically check whether their descriptor values turn out as expected. 
For methods that are not easily tested (e.g. the plotting methods), it might be enough to run them within a test method to check whether they do not throw an exception. 

This is all that spontaneously came to my mind. For further input on testing with PyTest, I am including our "expert" in this conversation, @OBrink .

Was this helpful and understandable so far? And sorry that I/we did not find time to review your code updates yet.

**Comment by hannbus** [comment]
Thanks a lot! That was indeed helpful! And don't stress yourself with the reviewing.

I added the notebook where I tried the first version of the functions and the respective test data in the Workflow folder. Maybe you can have a look at that as well to see if it is okay like that.

**Comment by JonasSchaub** [comment]
Thank you, I will have a look at it when I find the time!
Don't act on it now, but I suspect unit tests are actually better placed in a .py file instead of a Jupyter Notebook, so that they can be executed together in one go. But that is again a question to the Python experts here (which is definitely not me).

**Comment by hannbus** [comment]
Okay, I will change the functions into a python file. Thanks for the explanation!

**Comment by JonasSchaub** [comment]
Another thing: I think the testing code should go into its own folder in the repository root. I would not locate it in the "Workflow" folder where it is now.

**Comment by hannbus** [comment]
I added a new folder 'Tests' and inside I put the python file with the unit tests. The notebook in the Workflow folder is deleted. For some functions I don't have tests yet but I will think about something. One test is constantly failing and I don't know why. So I commented it out for now and will look into it.
I did not put all the test functions in a class as in the example from the RanDepict repository. Do you think I should change this or is it okay to leave it like this?

**Comment by OBrink** [comment]
Nice. Having the tests in a separate directory definitely is a good structure. 

I normally like to wrap up my tests in a class if that means that I can avoid global variables, but it should also work the way you did it. 

About the failing test: Could you try replacing line 25 with...
testdict = cider.draw_molecules(testdict, number_of_mols = 2)
Does that work? I would assume that your class method does not have the right to alter the global variable "testdict". On the other hand, it seems to work in the previous test "test_get_number_of_molecules()".

One general remark:
"assert XY == True" 
can simply be written as
"assert XY"
In that case, the "== True" is implicitly included automatically and is often considered redundant.

**Comment by hannbus** [comment]
Thanks for the fast suggestion for a solution, but unfortunally it does not solve the problem.
Another thing is, that I get a lot of warnings (about 116) when running the tests. Is this a serious problem?

And also thanks for the general remark, as of now I will leave it out.

**Comment by OBrink** [comment]
116 warnings? I guess it depends on what they say, but that sounds like a lot :D

**Comment by JonasSchaub** [comment]
Just noting it here for the moment so we do not forget it: We need to include pytest in the installation.

**Comment by Kohulan** [comment]
@JonasSchaub I don't think it is necessary to include pytest in the installation, it is used only in GitHub for testing

**Comment by OBrink** [comment]
I have added it in the requirements

**Comment by JonasSchaub** [comment]
You guys are always answering way too fast...

**Comment by OBrink** [comment]
If the user wants to run the tests, they need it

**Comment by JonasSchaub** [comment]
I think its important to be able to run the tests locally as well

**Comment by OBrink** [comment]
But before this gets lost in the other messages: 
@hannbus: What are the 116 warnings about?

**Comment by JonasSchaub** [comment]
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\setuptools\_distutils\version.py:351
  C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\setuptools\_distutils\version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

Anybody knows spontaneously what this tells us and how to fix it?

**Comment by JonasSchaub** [comment]
Because these warnings tell us that some library used in a 3rd party package we are using will be deprecated soon, they are not of relevance to use. We can ignore them, I'd say. 

To suppress the output of such "DeprecationWarning"s in pytest, you can add the following lines to the tox.ini file:

[pytest]
filterwarnings =
    ignore::DeprecationWarning

found here: https://stackoverflow.com/questions/40710094/how-to-suppress-py-test-internal-deprecation-warnings

I tried it and it works, down to zero warnings when ignoring the DeprecationWarning.

**Comment by hannbus** [comment]
Thanks! I added that into the file. While doing so I noticed that in the tox.ini file there are still the old folder names and the notebook with the old name 'Praktikum_V3' under [flake8]. Should I also change those to the new names?

**Comment by OBrink** [comment]
That seems reasonable to me

**Comment by hannbus** [comment]
I wrote tests for all the "main" functions. With this I mean the functions that will be used when one does actually work with CIDER (e.g. descriptor_counts_and_plot). For the functions that will be called in the background (e.g. discrete_descriptor_plot) I did not write test functions so far but they are indirect tested through testing the "main" functions. Should there be explicit tests for those background functions?

**Comment by OBrink** [comment]
I would claim that small, specific tests are important to make sure that everything on every level of your application really behaves the way we want it to behave. If you find the time, I would write tests for every function.
__ 
In the future, I would recommend sticking to **test-driven development** for the implementation of new features in CIDER:
The idea here is that for every function that you write, you first write a unit test. 
This means of course, that at the beginning, you have one or more failing tests for every case that the function is supposed to work with.
Then, you write a function that fulfils whatever the tests are testing.
__
Test-driven development is the industry standard when it comes to writing clean and robust code. If done properly, we can keep the test coverage close to 100%.
